### ISSUE TITLE
Deprecated auth through query param 

### ISSUE THREAD

**Issue by ruisaraiva19** [wilau2/circleci-validate-commit-msg#14]
I just received an email regarding a deprecation on the GitHub API v3.

![Screenshot 2020-03-27 at 14 00 47](https://user-images.githubusercontent.com/7356098/77764164-191a8480-7034-11ea-8193-ee74885cfd20.jpg)

I can open a pull request with the recommended change for this.

**Comment by wilau2** [comment]
@ruisaraiva19 it would be appreciated!

**Comment by ruisaraiva19** [comment]
Ok, later today I'll work on this 🙂.

**Comment by wilau2** [comment]
@ruisaraiva19 

The latest image have been deploy, let me know if you have any other issues.

**Comment by ruisaraiva19** [comment]
Sounds good!
